"""Validated, versioned Local Recall configuration."""

from .errors import (
    ConfigurationError,
    ConfigurationLoadError,
    ConfigurationMigrationError,
    UnsupportedSchemaVersion,
)
from .inspection import inspect_effective_configuration
from .loader import (
    LoadedConfiguration,
    configuration_revision,
    load_configuration_file,
    load_configuration_mapping,
)
from .manager import ConfigurationManager, ConfigurationSnapshot, ReloadOutcome
from .migrations import migrate_configuration
from .models import (
    CURRENT_SCHEMA_VERSION,
    MAX_POLICY_PATTERN_LENGTH,
    MAX_POLICY_RULES,
    ActivityWatchSettings,
    ActivityWatchURLMode,
    CaptureOverloadPolicy,
    CaptureRule,
    CaptureSettings,
    CredentialReference,
    CustomRedactionPattern,
    EncryptionSettings,
    HighEntropySettings,
    LocalRecallConfig,
    MetadataSettings,
    ModelSettings,
    OCRSettings,
    PolicyTimeWindow,
    PrivacyProfile,
    RedactionAllowlist,
    RedactionSettings,
    RemoteProviderSettings,
    RetentionSettings,
    RuleEffect,
    RuleSettings,
    StorageSettings,
)

__all__ = [
    "CURRENT_SCHEMA_VERSION",
    "MAX_POLICY_PATTERN_LENGTH",
    "MAX_POLICY_RULES",
    "ActivityWatchSettings",
    "ActivityWatchURLMode",
    "CaptureOverloadPolicy",
    "CaptureRule",
    "CaptureSettings",
    "ConfigurationError",
    "ConfigurationLoadError",
    "ConfigurationManager",
    "ConfigurationMigrationError",
    "ConfigurationSnapshot",
    "CredentialReference",
    "CustomRedactionPattern",
    "EncryptionSettings",
    "HighEntropySettings",
    "LoadedConfiguration",
    "LocalRecallConfig",
    "MetadataSettings",
    "ModelSettings",
    "OCRSettings",
    "PolicyTimeWindow",
    "PrivacyProfile",
    "RedactionAllowlist",
    "RedactionSettings",
    "ReloadOutcome",
    "RemoteProviderSettings",
    "RetentionSettings",
    "RuleEffect",
    "RuleSettings",
    "StorageSettings",
    "UnsupportedSchemaVersion",
    "configuration_revision",
    "inspect_effective_configuration",
    "load_configuration_file",
    "load_configuration_mapping",
    "migrate_configuration",
]
