"""Bounded metadata source implementations."""

from .activitywatch import ActivityWatchMetadataSource
from .activitywatch_client import LocalActivityWatchClient
from .activitywatch_http import LoopbackActivityWatchTransport
from .activitywatch_types import (
    ActivityWatchAdapterFailure,
    ActivityWatchBucket,
    ActivityWatchEvent,
    ActivityWatchEventType,
    ActivityWatchMetadataFailure,
    ActivityWatchMetadataFailureCode,
    ActivityWatchServerInfo,
)
from .qtile import (
    FixedQtileCommandRunner,
    QtileAdapterFailure,
    QtileCommand,
    QtileCommandReader,
    QtileCommandResult,
    QtileCommandRunner,
    QtileExecutablePath,
    QtileMetadataFailure,
    QtileMetadataFailureCode,
    QtileMetadataSource,
    QtileSnapshot,
    QtileSnapshotReader,
)
from .xorg import (
    FixedXorgCommandRunner,
    GenericXorgMetadataSource,
    XorgAdapterFailure,
    XorgCommand,
    XorgCommandResult,
    XorgCommandRunner,
    XorgExecutablePaths,
    XorgMetadataFailure,
    XorgMetadataFailureCode,
    XorgPropertyReader,
    XorgWindowProperties,
    XpropXorgPropertyReader,
)

__all__ = [
    "ActivityWatchAdapterFailure",
    "ActivityWatchBucket",
    "ActivityWatchEvent",
    "ActivityWatchEventType",
    "ActivityWatchMetadataFailure",
    "ActivityWatchMetadataFailureCode",
    "ActivityWatchMetadataSource",
    "ActivityWatchServerInfo",
    "FixedQtileCommandRunner",
    "FixedXorgCommandRunner",
    "GenericXorgMetadataSource",
    "LocalActivityWatchClient",
    "LoopbackActivityWatchTransport",
    "QtileAdapterFailure",
    "QtileCommand",
    "QtileCommandReader",
    "QtileCommandResult",
    "QtileCommandRunner",
    "QtileExecutablePath",
    "QtileMetadataFailure",
    "QtileMetadataFailureCode",
    "QtileMetadataSource",
    "QtileSnapshot",
    "QtileSnapshotReader",
    "XorgAdapterFailure",
    "XorgCommand",
    "XorgCommandResult",
    "XorgCommandRunner",
    "XorgExecutablePaths",
    "XorgMetadataFailure",
    "XorgMetadataFailureCode",
    "XorgPropertyReader",
    "XorgWindowProperties",
    "XpropXorgPropertyReader",
]
